# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
        
    - name: Download libs
      run: go get -u github.com/fsnotify/fsnotify && go get -u github.com/gorilla/websocket
      
    - name: Add libs
      run: go get app/app

    - name: Build
      run: cd app && go build -v ./...

    - name: Test
      run: cd app && go test -v ./...
