jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.5
    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download libs
      run: go get -u github.com/fsnotify/fsnotify && go get -u github.com/gorilla/websocket
    - name: Add libs
      run: go get app/app
    - name: Build
      run: cd app && go build -v -o bin/myapp
    - name: Test
      run: cd app && go test -v ./...
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: app/bin/myapp
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: app/bin/myapp
name: Go release
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
